language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"

services:
  - docker

before_install:
  - docker pull cassandra:2.1
  - docker run --name cassandra -p 127.0.0.1:9042:9042 -p 127.0.0.1:9160:9160 -d cassandra:2.1

install:
  - pip install six
  - pip install cassandra-driver

script:
  - cd tests
  - make t1
  - make t2
  - make t3
  - make t4
  - make t5
  - make t6
  - make t7
  - make t8
  - make t9
  - make t10
