language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"

services:
  - docker

before_install:
  - docker pull cassandra:2.1
  - docker run --name cassandra -p 127.0.0.1:9042:9042 -p 127.0.0.1:9160:9160   -d cassandra:2.1

script: 
  - ./tests/run_tests.sh
